
if not minetest.global_exists("dryleaves") then dryleaves = {} end
dryleaves.modpath = minetest.get_modpath("dryleaves")

dryleaves.list = {
	"dryleaves:leaves",
	"dryleaves:jungleleaves",
	"dryleaves:dry_leaves",
	"dryleaves:plantlike",
}



reload.register_file("dryleaves:core", dryleaves.modpath .. "/functions.lua", true)



minetest.register_node("dryleaves:leaves", {
	description = "Dry Leaves",
	drawtype = "plantlike",
	waving = 1,
	visual_scale = 1.4,
	walkable = false,

	tiles = {"dryleaves_leaves.png"},
	paramtype = "light",
	groups = utility.dig_groups("leaves", {leafdecay = 3, flammable = 3, leaves = 1, dry_leaves = 1}),
	sounds = default.node_sound_leaves_defaults(),
	movement_speed_multiplier = default.SLOW_SPEED_PLANTS,
  
  on_construct = enhanced_leafdecay.make_leaf_constructor({}),
  on_timer = enhanced_leafdecay.make_leaf_nodetimer({}),
})



minetest.register_node("dryleaves:jungleleaves", {
	description = "Dry Leaves",
	drawtype = "plantlike",
	waving = 1,
	visual_scale = 1.4,
	walkable = false,

	tiles = {"dryleaves_jungleleaves.png"},
	paramtype = "light",
	groups = utility.dig_groups("leaves", {leafdecay = 3, flammable = 3, leaves = 1, dry_leaves = 1}),
	sounds = default.node_sound_leaves_defaults(),
	movement_speed_multiplier = default.SLOW_SPEED_PLANTS,
  
  on_construct = enhanced_leafdecay.make_leaf_constructor({}),
  on_timer = enhanced_leafdecay.make_leaf_nodetimer({}),
})



minetest.register_node("dryleaves:dry_leaves", {
	description = "Dry Leaves",
	drawtype = "plantlike",
	waving = 1,
	visual_scale = 1.4,
	walkable = false,
	tiles = {"darkage_dry_leaves.png"},
	paramtype = "light",
	groups = utility.dig_groups("leaves", {leafdecay = 3, flammable = 3, leaves = 1, dry_leaves = 1}),
	sounds = default.node_sound_leaves_defaults(),
	movement_speed_multiplier = default.SLOW_SPEED_PLANTS,

	on_construct = enhanced_leafdecay.make_leaf_constructor({}),
	on_timer = enhanced_leafdecay.make_leaf_nodetimer({}),
})



minetest.register_node("dryleaves:plantlike", {
	description = "Dry Leaves",
	drawtype = "plantlike",
	waving = 1,
	visual_scale = 1.4,
	walkable = false,

	tiles = {"default_leaves_plantlike.png"},

	paramtype = "light",
	groups = utility.dig_groups("leaves", {leafdecay = 3, flammable = 3, leaves = 1, dry_leaves = 1}),

	sounds = default.node_sound_leaves_defaults(),
	movement_speed_multiplier = default.SLOW_SPEED_PLANTS,

	on_construct = enhanced_leafdecay.make_leaf_constructor({}),
	on_timer = enhanced_leafdecay.make_leaf_nodetimer({}),
})


-- All leaf variants are present in Channelwood (generated by mapgen).
